spring:
    application:
        name: music-service

aws:
    s3:
        endpoint: https://s3.twcstorage.ru
        region: ru-1
        access-key: ${S3_ACCESS_KEY:}
        secret-key: ${S3_SECRET_KEY:}
        bucket: ${S3_BUCKET:}